### ISSUE TITLE
Optionally use hardlinks instead of symlinks

### ISSUE THREAD

**Issue by catern** [andsens/homeshick#145]
Some software gets confused when its configuration files are symlinks (systemd --user, for one, but I've run into it with other things as well). And some software treats symlinks in a way that is undesirably different from normal files.

These problems would go away if homeshick could optionally use hardlinks instead of symlinks. If that sounds like a reasonable feature I'll whip up a patch and submit it.

**Comment by andsens** [comment]
> Some software gets confused when its configuration files are symlinks 

I know, it sucks. Compat with symlinks should be a reasonable expectation, but it seems not to be the case everywhere.

> These problems would go away if homeshick could optionally use hardlinks instead of symlinks.

Not if you do something like an atomic write where you run `echo 'new config' > tempfile; mv tempfile configfile`.

> If that sounds like a reasonable feature I'll whip up a patch and submit it.

You are going to have quite a bit of trouble with that, since homeshick needs to know whether an existing file points to a castle - I don't think that's possible with hardlinks. Also, how would you configure whether a file is to be symlinked or hardlinked. Configfiles are not an option, they are something I have avoided vehemently in homeshick, everything should be configurable directly through the filesystem/[linking table](https://github.com/andsens/homeshick/wiki/Symlinking#linking-table).

**Comment by catern** [comment]
>You are going to have quite a bit of trouble with that, since homeshick needs to know whether an existing file points to a castle - I don't think that's possible with hardlinks.

Could just check the inode number. Simple, easy.

**Comment by andsens** [comment]
> Could just check the inode number. Simple, easy.

Huh, of course. Nice solution :-)

I'd be open to a PR if you could solve the other problems I mentioned.

Have you tested whether using hardlinks actually solves the problem?

**Comment by andsens** [comment]
This is a rather old request. Have you solved your problem? I'm closing this for now, feel free to reopen if you have any comments/ideas that could overcome this challenge.

**Comment by leoj3n** [comment]
I've had some programs clobber symlinked config files as well but can't remember specifically which ones.
