### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by oreinert** [andsens/homeshick#180]
It's been 3 years since the last version of homeshick, and there's been some activity since then.
Would it make sense to make a version of those changes now?

**Comment by andsens** [comment]
I only tag a version for [the benefit of package maintainers](https://github.com/andsens/homeshick/wiki/Packages#versioning) (it's available in homebrew, OpenSUSE and ArchLinux). There is no need for versioning otherwise, since all homeshick versions so far are backwards compatible (and excepting a few very early commits forwards compatible as well).

**Comment by oreinert** [comment]
Ok, in that case: As the maintainer of the openSUSE package of homeshick, I would like to kindly ask you to assign a version number to the current stable state.

**Comment by andsens** [comment]
Haha, I didn't recognise your name, sorry about that :-)
[v1.1.0](https://github.com/andsens/homeshick/releases/tag/v1.1.0) is now available and tagged (including a few details on the changes).

**Comment by oreinert** [comment]
No problem - it's been a while. :-)
Thanks - especially for the changelist, that's very helpful.
