### ISSUE TITLE
Naming differences

### ISSUE THREAD

**Issue by binarykitchen** [andsens/homeshick#203]
Why it is sometimes called homeshick, then homesick? Nowhere mentioned in install instructions. Thanks for explaining.

**Comment by andsens** [comment]
Hi there, it's only called `homesick` without an `s` in the path. This was originally to support compatibility with [homesick](https://github.com/technicalpickles/homesick) by technicalpickles. I think if there were to be a major revision of homeshick that compatibility would be dropped in favor of consistency, but for now we're stuck with that.

**Comment by binarykitchen** [comment]
@andsens ok, I get it. Recommend two things:
- document this somewhere
- provide your own `apt-get install` for Linux machines cos it interfers with the naming

**Comment by andsens** [comment]
> document this somewhere

[It is](https://github.com/andsens/homeshick/wiki/homeshick-and-homesick)

> provide your own apt-get install for Linux machines cos it interfers with the naming

homeshick is made to be user installable in order to not require any root privileges. However, there are packages for [Arch](https://aur.archlinux.org/packages/homeshick-git/), [SUSE](https://packagehub.suse.com/packages/homeshick/), and [homebrew](https://formulae.brew.sh/formula/homeshick). These packages were made to scratch some specific itches, but I am not the maintainer of those and am not looking to take on any package maintenance. If you would like to maintain a dpkg you are welcome to do so, [it's even documented a little](https://github.com/andsens/homeshick/wiki/Packages).

**Comment by binarykitchen** [comment]
Ah thanks man, I must have missed that out. Understand now.
